[book]
authors = ["Umesh Kumar Singh"]
language = "en"
src = "src"
title = "Hello World"
description = "Fist MDBook doc created by me"


[build]
build-dir = "book"                # the directory where the output is placed
create-missing = true             # whether or not to create missing pages
use-default-preprocessors = true  # use the default preprocessors
extra-watch-dirs = []             # directories to watch for triggering builds



[output.html.playground]
editable = true

[output.html]
default-theme = "light"
preferred-dark-theme = "navy"
smart-punctuation = true
mathjax-support = true
no-section-label = true
git-repository-url = "https://github.com/qbit-glitch/mdbook_hello_world"
site-url = "https://qbit-glitch.github.io/mdbook_hello_world/"
input-404 = "not-found.md"
editable = true         # allows editing the source code
copyable = true          # include the copy button for copying code snippets
line-numbers = true     # displays line numbers for editable code
runnable = true          # displays a run button for rust code

[output.html.print]
enable = true    # include support for printable output
page-break = true # insert page-break after each chapter

[output.html.fold]
enable = true    # whether or not to enable section folding
level = 0         # the depth to start folding
